Temp fix: Followup hang
mentorpal/mentor-admin pull request #102
Opened 2021-08-05 16:37 UTC by aaronshiel

2021-08-05 23:38 UTC, beatthat requested changes
looks good. before merge

- [x] get review from @kycarr (since touching `useActiveMentor`)
- [ ] make small requested changes
- [ ] make sure this PR merges to a (maybe new) `careerfair-integration` branch (not main)

2021-08-05 23:38 UTC, beatthat commented on client/src/hooks/graphql/use-with-record-state.tsx
> +      let followUps = data
```typescript
setFollowups((data || []).map(...).filter(...))
```

2021-08-05 23:43 UTC, kycarr approved these changes

2021-08-06 22:00 UTC, beatthat approved these changes

2021-08-06 22:13 UTC, merged