Merged with main
mentorpal/mentor-admin pull request #123
Opened 2021-08-18 22:28 UTC by supersweet-dev

2021-08-18 23:17 UTC, beatthat requested changes
still not passing all tests...need other eyes to fix?

2021-08-18 23:19 UTC, supersweet-dev commented
> still not passing all tests...need other eyes to fix?

yeah, cypress tests are flaky all over and I'm getting query syntax errors when testing locally

2021-08-19 00:02 UTC, beatthat requested changes
looks good...maybe a few tiny changes to be cleaner in cypress expectations (see inline). After that I vote merge

2021-08-19 00:17 UTC, beatthat approved these changes

2021-08-19 00:26 UTC, merged