followups refactor
mentorpal/mentor-admin pull request #125
Opened 2021-08-19 22:27 UTC by aaronshiel

The follow ups widget was once a component that lived in the record page. I moved it to its own page with its own hooks.

2021-08-19 23:03 UTC, beatthat reviewed
question: everywhere else we do array params this style: `?mentor=m1&mentor=m2`

...what drives doing them comma separated now?

2021-08-19 23:08 UTC, aaronshiel commented
> question: everywhere else we do array params this style: `?mentor=m1&mentor=m2`
> 
> ...what drives doing them comma separated now?

You can specify a parameter `arrayFormat` to queryString.parse() (which I did in use-with-location.tsx)

I wasn't aware of the format you specified.

2021-08-19 23:11 UTC, beatthat commented
> > question: everywhere else we do array params this style: `?mentor=m1&mentor=m2`
> > ...what drives doing them comma separated now?
> 
> You can specify a parameter `arrayFormat` to queryString.parse() (which I did in use-with-location.tsx)
> 
> I wasn't aware of the format you specified.

wondering if would be hard to make it work the other way? Just because we do it that way everywhere else (e.g. multiple mentors for a mentor panel and list of recommended questions)

2021-09-09 19:52 UTC, kycarr requested changes

2021-09-09 19:52 UTC, kycarr commented on cypress/cypress/integration/followups.spec.ts
> +          question: completeQuestion({
The way questions are fetched has changed somewhat, so subject only needs the _id and not the other stuff for questions:

questions: [completeSubjectQuestion({category: {id: "cat"}, topics: [], question: {_id: "A1_1_1}})]

2021-09-09 19:52 UTC, kycarr commented on cypress/cypress/integration/followups.spec.ts
> +            question: "How old are you now?",
can remove question field here

2021-09-09 19:52 UTC, kycarr commented on cypress/cypress/integration/followups.spec.ts
> +            question:
can remove question field from question here

2021-09-09 19:52 UTC, kycarr commented on cypress/cypress/integration/followups.spec.ts
> +        question: "Who are you and what do you do?",
Same here, question in answer only needs _id (remove question text field)

2021-09-09 23:00 UTC, kycarr approved these changes

2021-09-10 00:10 UTC, merged