Manage user roles page
mentorpal/mentor-admin pull request #80
Opened 2021-07-20 01:56 UTC by aaronshiel

2021-07-26 22:17 UTC, beatthat requested changes
looks good. TODO:

- [x] merge main back to this branch (or rebase onto main)
- [x] update gql query names to match `users` not `fetchUsers`
- [x] cut an alpha release docker image
- [x] test locally w latest in 4.2.x-release 

Once the above all confirmed, let me know and I will merge/deply to v2

2021-07-26 22:21 UTC, beatthat requested changes
couple additional notes

2021-07-26 22:21 UTC, beatthat commented on client/src/api.ts
> +  return result.data.data;
don't assume GQL requests succeed. You have to check for errors, we should probably have a generic helper function for this

2021-07-26 22:21 UTC, beatthat commented on client/src/api.ts
> +  return result.data.data.me.updateUserPermissions;
check for errors (have a test for how errors are handled and then make it work here)

2021-07-27 20:47 UTC, beatthat requested changes
looks great. A few very small change requests inline, and then (assuming this is tested locally w an alpha release?) ready to merge/deploy

2021-07-27 20:47 UTC, beatthat commented on client/src/api.ts
> +  if ("me" in res.data.data) return res.data.data.me;
the whole `me` thing makes some misery, but we may as well deal w it correctly, e.g.

```typescript
interface Me<T> {
  me: T
}
```

2021-07-27 20:47 UTC, beatthat commented on client/src/components/nav-bar.tsx
> +    state.user?.userRole == UserRole.CONTENT_MANAGER;
`===`

2021-07-27 20:47 UTC, beatthat commented on client/src/hooks/graphql/use-with-users.tsx
> +  function fetch() {
needs return type

2021-07-27 20:47 UTC, beatthat commented on client/src/hooks/graphql/use-with-users.tsx
> +  function onUpdateUserPermissions(userId: string, permissionLevel: string) {
even though i think is just `void` still put the return type

2021-07-27 20:47 UTC, beatthat commented on client/src/pages/users.tsx
> +  function handleLaunchMentor(mentorId: string) {
ok, just scanning this PR, I've noticed two distinct functions that launch a mentor. Find all such functions and replace them with a single, importable helper function, e.g. `launchMentor(mentorID: string)`

2021-07-28 01:03 UTC, beatthat requested changes
looks great! One or two more tiny change requests inline + sent a PR for `execGQL` update. After those, I think we're good to go

2021-07-28 01:03 UTC, beatthat commented on client/src/hooks/graphql/use-with-users.tsx
> +  userDataError: LoadingError | undefined;
generally prefer we just use built in typescript for optional types, e.g. `userDataError?: LoadingError`

2021-07-28 22:02 UTC, aaronshiel commented
tested with alpha release 4.2.0-alpha.21

2021-07-28 23:18 UTC, closed without merging